/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ApplicationGestion;

import Tools.FilesOperations;
import network.NetworkBasicClient;
import network.NetworkBasicServer;

import javax.swing.*;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Objects;
import java.util.Properties;

public class CommandePieces extends javax.swing.JDialog implements Runnable {

    /**
     * Creates new form CommandePieces
     */
    private NetworkBasicClient Client;
    private NetworkBasicServer Serveur;
    private boolean ExistModel = false; // détermine si un model pour la jliste existe deja ou non
    private String Ip;
    private int Port;
    private int PortClient;
    private String MessageEtat;
    private Thread ThLecture;
    private boolean ServeurState;
    /**
     * @param parent
     * @param modal
     * @param type
     */
    public CommandePieces(java.awt.Frame parent, boolean modal, int type) {
        super(parent, modal);
        initComponents();
        final Properties temp = new Properties();
        try {
            temp.load(new FileInputStream(FilesOperations.PROPERTIES));
        } catch (IOException e) {
            e.printStackTrace();
            System.exit(-1);
        }
        Ip = temp.getProperty("IP");
        PortClient = Integer.parseInt(temp.getProperty("portClient"));
        switch(type)
        {
            //Si pneus
            case 1:
                Port = Integer.parseInt(temp.getProperty("Pneus"));
                break;
            //Si pièces
            case 2:
                Port = Integer.parseInt(temp.getProperty("Piece"));
                break;
            //Si lubrifiant
            case 3:
                Port = Integer.parseInt(temp.getProperty("Lubrifiant"));
                break;
        }
        Serveur = new NetworkBasicServer(PortClient, null);
        _etatServeurLabel.setText("Etat du serveur: On");
        Client = new NetworkBasicClient(Ip, Port);
        ServeurState = true;
        String message = String.format("Connexion;127.0.0.1;%d", PortClient);
        message = Client.sendString(message);
        if (!Objects.equals(message, "OK"))
            System.exit(0);
        ThLecture = new Thread(() -> {
            String mess;
            while (true)
                {
                    if ((mess = Serveur.getMessage()).equals("RIEN")) {
                        try {
                            Thread.sleep(1);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    } else {
                        System.err.println("ThLecture> Message reçu : " + mess);
                        if (mess.contains("Pause"))
                        {
                            ServeurState = false;
                            _etatServeurLabel.setText("Etat du serveur: Off");
                        }
                        else if (mess.contains("Ligne"))
                        {
                            ServeurState = true;
                            _etatServeurLabel.setText("Etat du serveur: On");
                        }
                        this.repaint();
                    }
                }
        });
        ThLecture.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _commandeLabel = new javax.swing.JLabel();
        _urgentRB = new javax.swing.JRadioButton();
        _normalRB = new javax.swing.JRadioButton();
        _nonPrioritaireRB = new javax.swing.JRadioButton();
        _commandesLabel = new javax.swing.JLabel();
        _libelléLabel = new javax.swing.JLabel();
        _typeLabel = new javax.swing.JLabel();
        _quantiteLabel = new javax.swing.JLabel();
        _libelleTF = new javax.swing.JTextField();
        _typeTF = new javax.swing.JTextField();
        _quantitéTF = new javax.swing.JTextField();
        _envoyerButton = new javax.swing.JButton();
        annulerButon = new javax.swing.JButton();
        _scrollpanel = new javax.swing.JScrollPane();
        _commandesList = new javax.swing.JList<>();
        _etatServeurLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        _commandeLabel.setText("Commande :");
        _commandeLabel.setToolTipText("");

        _urgentRB.setText("Urgent");
        _urgentRB.setToolTipText("");
        _urgentRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _urgentRBActionPerformed(evt);
            }
        });

        _normalRB.setText("Normal");
        _normalRB.setToolTipText("");
        _normalRB.setActionCommand("NormalRB");
        _normalRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _normalRBActionPerformed(evt);
            }
        });

        _nonPrioritaireRB.setText("Non Prioritaire");
        _nonPrioritaireRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _nonPrioritaireRBActionPerformed(evt);
            }
        });

        _commandesLabel.setText("Commandes :");

        _libelléLabel.setText("Libellé :");

        _typeLabel.setText("Type :");

        _quantiteLabel.setText("Quantité :");

        _envoyerButton.setText("Envoyer");
        _envoyerButton.setToolTipText("");
        _envoyerButton.setActionCommand("EnvoyerButton");
        _envoyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _envoyerButtonActionPerformed(evt);
            }
        });

        annulerButon.setText("Annuler");
        annulerButon.setToolTipText("");
        annulerButon.setActionCommand("AnnulerButton");
        annulerButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButonActionPerformed(evt);
            }
        });

        _scrollpanel.setViewportView(_commandesList);

        _etatServeurLabel.setText("Etat du serveur: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(_envoyerButton)
                .addGap(108, 108, 108)
                .addComponent(annulerButon)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_urgentRB)
                                .addGap(33, 33, 33)
                                .addComponent(_normalRB)
                                .addGap(50, 50, 50)
                                .addComponent(_nonPrioritaireRB))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_libelléLabel)
                                    .addComponent(_typeLabel)
                                    .addComponent(_quantiteLabel))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(_libelleTF)
                                    .addComponent(_typeTF)
                                    .addComponent(_quantitéTF, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(_commandeLabel)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_scrollpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_commandesLabel)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_etatServeurLabel)
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_commandeLabel)
                    .addComponent(_etatServeurLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_urgentRB)
                    .addComponent(_normalRB)
                    .addComponent(_nonPrioritaireRB)
                    .addComponent(_commandesLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_libelléLabel)
                            .addComponent(_libelleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_typeLabel)
                            .addComponent(_typeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_quantiteLabel)
                            .addComponent(_quantitéTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_scrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_envoyerButton)
                    .addComponent(annulerButon))
                .addGap(21, 21, 21))
        );

        _commandeLabel.getAccessibleContext().setAccessibleName("CommandeLabel");
        _commandesLabel.getAccessibleContext().setAccessibleName("CommandesLabel");
        _libelléLabel.getAccessibleContext().setAccessibleName("LibelléLabel");
        _typeLabel.getAccessibleContext().setAccessibleName("TypeLabel");
        _quantiteLabel.getAccessibleContext().setAccessibleName("QuantitéLabel");
        _quantiteLabel.getAccessibleContext().setAccessibleDescription("");
        _libelleTF.getAccessibleContext().setAccessibleName("LibelleTF");
        _typeTF.getAccessibleContext().setAccessibleName("TypeTF");
        _quantitéTF.getAccessibleContext().setAccessibleName("QuantiteTF");
        _quantitéTF.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param evt
     */
    private void _envoyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__envoyerButtonActionPerformed
        String reponse;
        String envoiMessage;
        String disponibilite;
        if (ServeurState)
        {
            envoiMessage = _libelleTF.getText() + ";" + _typeTF.getText() + ";" + _quantitéTF.getText();
            //On ajoute à la liste des commandes
            DefaultListModel<String> dlm = new DefaultListModel<>();
            if(!ExistModel)
            {
                _commandesList.setModel(dlm);
                ExistModel = true;
            }
            dlm = (DefaultListModel<String>)_commandesList.getModel();
            dlm.addElement(envoiMessage);
            _commandesList.setModel(dlm);

            //Clear champs
            _libelleTF.setText("");
            _typeTF.setText("");
            _quantitéTF.setText("");

            //Envoi d'un message avec attente bloquante de la réponse.
            reponse = Client.sendString(envoiMessage);
            //Envoi d'un message sans attente bloquante (simple notif)
            //client.sendStringWithoutWaiting(envoiMessage);

            String[] parts = reponse.split(";");
            disponibilite = parts[0];

            if(disponibilite.compareTo("true") == 0)
                JOptionPane.showMessageDialog(this, "OK pour\n " + parts[1] + ", " + parts[2] + ", " + parts[3], "Information", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(this, "Plus de stock pour\n " + parts[1] + ", " + parts[2] + ", " + parts[3], "Attention", JOptionPane.WARNING_MESSAGE);

        }
        else
            JOptionPane.showMessageDialog(this,"Le serveur ne reçoit plus de requêtes pour le moment.","Erreur",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event__envoyerButtonActionPerformed

    /**
     * @param evt
     */
    private void annulerButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButonActionPerformed
        dispose();
    }//GEN-LAST:event_annulerButonActionPerformed

    private void _urgentRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__urgentRBActionPerformed
        _normalRB.setSelected(false);
        _nonPrioritaireRB.setSelected(false);
    }//GEN-LAST:event__urgentRBActionPerformed

    private void _normalRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__normalRBActionPerformed
        _nonPrioritaireRB.setSelected(false);
        _urgentRB.setSelected(false);
    }//GEN-LAST:event__normalRBActionPerformed

    private void _nonPrioritaireRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__nonPrioritaireRBActionPerformed
        _urgentRB.setSelected(false);
        _normalRB.setSelected(false);
    }//GEN-LAST:event__nonPrioritaireRBActionPerformed

    @Override
    public void run() {
        String message;

        while (true) {
            if ((message = Serveur.getMessage()).compareTo("RIEN") != 0) {
                MessageEtat = message;
                _etatServeurLabel.setText(MessageEtat);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | UnsupportedLookAndFeelException | IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommandePieces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            CommandePieces dialog = new CommandePieces(new JFrame(), true, 1);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _commandeLabel;
    private javax.swing.JLabel _commandesLabel;
    private javax.swing.JList<String> _commandesList;
    private javax.swing.JButton _envoyerButton;
    private javax.swing.JLabel _etatServeurLabel;
    private javax.swing.JTextField _libelleTF;
    private javax.swing.JLabel _libelléLabel;
    private javax.swing.JRadioButton _nonPrioritaireRB;
    private javax.swing.JRadioButton _normalRB;
    private javax.swing.JLabel _quantiteLabel;
    private javax.swing.JTextField _quantitéTF;
    private javax.swing.JScrollPane _scrollpanel;
    private javax.swing.JLabel _typeLabel;
    private javax.swing.JTextField _typeTF;
    private javax.swing.JRadioButton _urgentRB;
    private javax.swing.JButton annulerButon;
    // End of variables declaration//GEN-END:variables
}
