/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ApplicationGestion;

import java.util.Locale;

/**
 *
 * @author Nicolas
 */
public class Date extends javax.swing.JDialog {

    /**
     * @param parent
     * @param modal
     * Creates new form Date
     */
    public Date(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _paysComboBox = new javax.swing.JComboBox<>();
        _dateComboBox = new javax.swing.JComboBox<>();
        _tempsComboBox = new javax.swing.JComboBox<>();
        _tempsLabel = new javax.swing.JLabel();
        _dateLabel = new javax.swing.JLabel();
        _paysLabel = new javax.swing.JLabel();
        _titreLabel = new javax.swing.JLabel();
        _okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        _paysComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "France", "Royaume-Uni", "Allemagne", "Italie", "U.S.A" }));

        _dateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full", "Long", "Medium", "Short", " " }));

        _tempsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full", "Long", "Medium", "Short" }));

        _tempsLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        _tempsLabel.setText("Temps :");

        _dateLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        _dateLabel.setText("Date :");

        _paysLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        _paysLabel.setText("Pays :");

        _titreLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _titreLabel.setText("Formatage de la date");
        _titreLabel.setToolTipText("");

        _okButton.setText("OK");
        _okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_dateLabel)
                            .addComponent(_tempsLabel)
                            .addComponent(_paysLabel))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_paysComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_tempsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(_okButton)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(_titreLabel)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(_titreLabel)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_paysComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_paysLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_dateLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_tempsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_tempsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(_okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__okButtonActionPerformed
        Locale loc;
        switch (_paysComboBox.getSelectedIndex())
        {
            case 0:
                loc = Locale.FRANCE;
                break;
            case 1:
                loc = Locale.UK;
                break;
            case 2:
                loc = Locale.GERMANY;
                break;
            case 3:
                loc = Locale.ITALY;
                break;
            case 4:
                loc = Locale.US;
                break;
            default:
                loc = Locale.getDefault();
                break;
        }
        ((Panel)getParent()).setDate(loc,_dateComboBox.getSelectedIndex(),_tempsComboBox.getSelectedIndex());
        dispose();
    }//GEN-LAST:event__okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Date dialog = new Date(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> _dateComboBox;
    private javax.swing.JLabel _dateLabel;
    private javax.swing.JButton _okButton;
    private javax.swing.JComboBox<String> _paysComboBox;
    private javax.swing.JLabel _paysLabel;
    private javax.swing.JComboBox<String> _tempsComboBox;
    private javax.swing.JLabel _tempsLabel;
    private javax.swing.JLabel _titreLabel;
    // End of variables declaration//GEN-END:variables
}
