/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ApplicationGestion;

import People.Client;

import javax.swing.*;
import javax.swing.text.MaskFormatter;
import java.awt.*;
import java.text.ParseException;
import java.util.LinkedList;
import java.util.Vector;

import static java.lang.System.exit;

/**
 *
 * @author floryan
 */
public class NewWork extends javax.swing.JDialog {

    final private static String FORMAT = "#-UUU-###";

    private NewWork(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * @param parent Fenetre parent de cette fenêtre
     * @param modal Si la fenêtre est modale
     * @param clients Liste de touts les clients
     */
    public NewWork(Frame parent,boolean modal, LinkedList<Client> clients)
    {
        this(parent,modal);
        this._clientLinkedList = clients;
        for (Client temp : this._clientLinkedList)
            _clientsComboBox.addItem(temp);

        for (String temp : ENTRETIENT)
            _typeTravailCombo.addItem(temp);
        /*String[] listeCar = new String[]{"Alpha Roméo","Fiat","BMW","Volkswagen","Audi","Porsche","Suzuki","Nissan","Ford","Ferrari"};
        for(String temp : listeCar)
            _choixVoitureTextField.addItem(temp);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _jLabel1 = new javax.swing.JLabel();
        _jLabel2 = new javax.swing.JLabel();
        _jLabel3 = new javax.swing.JLabel();
        _jLabel4 = new javax.swing.JLabel();
        _jLabel5 = new javax.swing.JLabel();
        _clientsComboBox = new javax.swing.JComboBox<>();
        _typeTravailCombo = new javax.swing.JComboBox<>();
        _jScrollPane1 = new javax.swing.JScrollPane();
        _instructionTextArea = new javax.swing.JTextArea();
        _okButton = new javax.swing.JButton();
        _annulerButton = new javax.swing.JButton();
        _newCheckBox = new javax.swing.JCheckBox();
        _plaqueCheckBox = new javax.swing.JCheckBox();
        try{
            _immatriculationTextField = new javax.swing.JFormattedTextField(_maskFormatter = new MaskFormatter(FORMAT));
        } catch(Exception e)
        {
            exit(-1);
        }
        _entretienRadioButton = new javax.swing.JRadioButton();
        _reparationRadioButton = new javax.swing.JRadioButton();
        _choixVoitureTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nouveau travail");
        setResizable(false);
        setSize(new java.awt.Dimension(413, 327));
        setType(java.awt.Window.Type.UTILITY);

        _jLabel1.setText("Type de voiture: *");

        _jLabel2.setText("Immatriculation: *");

        _jLabel3.setText("Propriétaire: *");

        _jLabel4.setText("Type de travail: *");

        _jLabel5.setText("Instruction particulières: ");

        //TODO Editable + new

        _instructionTextArea.setColumns(20);
        _instructionTextArea.setRows(5);
        _jScrollPane1.setViewportView(_instructionTextArea);

        _okButton.setText("Ok");
        _okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _okButtonActionPerformed(evt);
            }
        });

        _annulerButton.setText("Annuler");
        _annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _annulerButtonActionPerformed(evt);
            }
        });

        _newCheckBox.setText("New !");
        _newCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _newCheckBoxActionPerformed(evt);
            }
        });

        _plaqueCheckBox.setSelected(true);
        _plaqueCheckBox.setText("Plaque Belge");
        _plaqueCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _plaqueCheckBoxActionPerformed(evt);
            }
        });

        _immatriculationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _immatriculationTextFieldActionPerformed(evt);
            }
        });

        _entretienRadioButton.setSelected(true);
        _entretienRadioButton.setText("Entretien");
        _entretienRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _entretienRadioButtonActionPerformed(evt);
            }
        });

        _reparationRadioButton.setText("Réparation");
        _reparationRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _reparationRadioButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel1.setText("* : Obligatoire");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_typeTravailCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(_entretienRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(_reparationRadioButton)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(_jLabel1)
                                            .addGap(18, 18, 18)
                                            .addComponent(_choixVoitureTextField))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(_jLabel3)
                                            .addGap(34, 34, 34)
                                            .addComponent(_clientsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(_jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(_immatriculationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 16, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_newCheckBox)
                            .addComponent(_plaqueCheckBox)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(_annulerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_jLabel1)
                    .addComponent(_choixVoitureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_jLabel2)
                    .addComponent(_plaqueCheckBox)
                    .addComponent(_immatriculationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_jLabel3)
                    .addComponent(_clientsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_newCheckBox))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_entretienRadioButton)
                    .addComponent(_reparationRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_jLabel4)
                    .addComponent(_typeTravailCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_jLabel5))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(_annulerButton)
                        .addComponent(_okButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__okButtonActionPerformed
        Vector<Object> retour = new Vector<>();
        if (_choixVoitureTextField.getText().isEmpty()
                || _immatriculationTextField.getText().isEmpty()
                || (_clientsComboBox.getSelectedIndex() == -1 && ((String)_clientsComboBox.getSelectedItem()).isEmpty())
                || _typeTravailCombo.getSelectedIndex() == -1)
            JOptionPane.showMessageDialog(this,"Il y a des champs obligatoire qui sont vide","Erreur",JOptionPane.ERROR_MESSAGE);
        else
        {
            retour.add(_choixVoitureTextField.getText());
            retour.add(_immatriculationTextField.getText());
            if (_clientsComboBox.getSelectedItem() instanceof Client)
                retour.add(_clientsComboBox.getSelectedItem());
            else
            {
                String[] np = ((String)_clientsComboBox.getSelectedItem()).split(" ");
                if (np.length >= 2)
                    retour.add(new Client(np[0],np[1],null,null,null));
                else if (np.length == 1)
                    retour.add(new Client(np[0],null,null,null,null));
            }
            retour.add((_entretienRadioButton.isSelected() ? "Entretiens " : "Réparation de/du" ) + _typeTravailCombo.getSelectedItem());
            retour.add(_instructionTextArea.getText());
            ((Panel)getParent()).ajout(retour,_entretienRadioButton.isSelected());
            dispose();
        }
    }//GEN-LAST:event__okButtonActionPerformed

    private void _plaqueCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__plaqueCheckBoxActionPerformed
        if (_plaqueCheckBox.isSelected())
            try {
                _maskFormatter.setMask(FORMAT);
            } catch (ParseException e) {
                e.printStackTrace();
            }
        else
            try {
                _maskFormatter.setMask("***************************");
            } catch (ParseException e) {
                e.printStackTrace();
            }
    }//GEN-LAST:event__plaqueCheckBoxActionPerformed

    private void _annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__annulerButtonActionPerformed
        dispose();
    }//GEN-LAST:event__annulerButtonActionPerformed

    private void _entretienRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__entretienRadioButtonActionPerformed
        _entretienRadioButton.setSelected(true);
        _reparationRadioButton.setSelected(false);
        _typeTravailCombo.removeAllItems();
        for (String temp: ENTRETIENT)
            _typeTravailCombo.addItem(temp);
    }//GEN-LAST:event__entretienRadioButtonActionPerformed

    private void _reparationRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__reparationRadioButtonActionPerformed
        _entretienRadioButton.setSelected(false);
        _reparationRadioButton.setSelected(true);
        _typeTravailCombo.removeAllItems();
        for(String temp: REPARATION)
            _typeTravailCombo.addItem(temp);
    }//GEN-LAST:event__reparationRadioButtonActionPerformed

    private void _newCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__newCheckBoxActionPerformed
        if (_newCheckBox.isSelected())
        {
            _position = _clientsComboBox.getSelectedIndex();
            _clientsComboBox.setSelectedIndex(-1);
            _clientsComboBox.setEditable(true);
        }
        else
        {
            _clientsComboBox.setSelectedIndex(_position);
            _clientsComboBox.setEditable(false);
        }
    }//GEN-LAST:event__newCheckBoxActionPerformed

    private void _immatriculationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__immatriculationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__immatriculationTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _annulerButton;
    private javax.swing.JTextField _choixVoitureTextField;
    private javax.swing.JComboBox<Client> _clientsComboBox;
    private javax.swing.JRadioButton _entretienRadioButton;
    private javax.swing.JFormattedTextField _immatriculationTextField;
    private javax.swing.JTextArea _instructionTextArea;
    private javax.swing.JLabel _jLabel1;
    private javax.swing.JLabel _jLabel2;
    private javax.swing.JLabel _jLabel3;
    private javax.swing.JLabel _jLabel4;
    private javax.swing.JLabel _jLabel5;
    private javax.swing.JScrollPane _jScrollPane1;
    private javax.swing.JCheckBox _newCheckBox;
    private javax.swing.JButton _okButton;
    private javax.swing.JCheckBox _plaqueCheckBox;
    private javax.swing.JRadioButton _reparationRadioButton;
    private javax.swing.JComboBox<String> _typeTravailCombo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private LinkedList<Client> _clientLinkedList;
    private MaskFormatter _maskFormatter;
    private int _position;

    private static final String[] ENTRETIENT = new String[]{"20000km","Changements pneus été","Changemenet pneus hiver"};

    private static final String[] REPARATION = new String[]{"Moteur","Bougies","Courroie de distribution","Climatisation","Parbrise"};
}
