/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ApplicationGestion;

import Activités.Travail;
import People.Client;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.Hashtable;
import java.util.Map;
import java.util.Vector;

/**
 *
 * @author flory
 */
public class PriseCharge extends javax.swing.JDialog {

    /**
     * Creates new form PriseCharge
     */
    private PriseCharge(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * @param parent
     * @param modal
     * @param liste
     * @param occupe
     */
    public PriseCharge(Frame parent, boolean modal, Hashtable<Vector<Object>,Boolean> liste, Travail[] occupe)
    {
        this(parent,modal);
        Liste = liste;
        ListeOccupe = occupe;
        miseTableau();
    }

    /**
     *
     */
    private void miseTableau()
    {
                                                        //Pour faire en sorte que le tableau ne soit pas modifiable
        DefaultTableModel dtm = new DefaultTableModel(){ @Override public boolean isCellEditable(int row, int column){return false;}};
        dtm.setColumnIdentifiers(new String[]{"Voiture","Immatriculation","Propriétaire","Travail","Remarques"});
        for (Map.Entry<Vector<Object>,Boolean> entry : Liste.entrySet())
            dtm.addRow(entry.getKey());
        Table.setModel(dtm);
    }

    /**
     * @param row
     * @return
     */
    private Vector<Object> getRow(int row)
    {
        Vector<Object> retour = new Vector<>();
        for (int n = 0; n < 5; n++)
            retour.add(Table.getValueAt(row,n));
        return retour;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        pontRadioButton = new javax.swing.JRadioButton();
        solRadioButton = new javax.swing.JRadioButton();
        pontComboBox = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        AnnulerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prise en charge d'un véhicule");
        setResizable(false);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table.setPreferredSize(new java.awt.Dimension(600, 64));
        Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Table);

        pontRadioButton.setSelected(true);
        pontRadioButton.setText("Pont");
        pontRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontRadioButtonActionPerformed(evt);
            }
        });

        solRadioButton.setText("Sol");
        solRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solRadioButtonActionPerformed(evt);
            }
        });

        pontComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        AnnulerButton.setText("Annuler");
        AnnulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Travaux en attente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pontRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(pontComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(solRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addGap(18, 18, 18)
                        .addComponent(AnnulerButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pontRadioButton)
                    .addComponent(solRadioButton)
                    .addComponent(pontComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(AnnulerButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param evt
     */
    private void pontRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontRadioButtonActionPerformed
        pontComboBox.setEnabled(true);
        pontRadioButton.setSelected(true);
        solRadioButton.setSelected(false);
    }//GEN-LAST:event_pontRadioButtonActionPerformed

    /**
     * @param evt
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (Table.getSelectedRowCount() == 1) {
            try{
                if (pontRadioButton.isSelected()){
                    ((Panel)getParent()).miseEnPlace(Integer.valueOf((String) pontComboBox.getSelectedItem()),getRow(Table.getSelectedRow()));
                }
                if (solRadioButton.isSelected()) {
                    ((Panel)getParent()).miseEnPlace(4,getRow(Table.getSelectedRow()));
                }
                dispose();
            } catch (PlaceUtilisee placeUtilisee) {
                JOptionPane.showMessageDialog(this,placeUtilisee.getMessage(),"Exception",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
            JOptionPane.showMessageDialog(this,"Veuillez sélectionner un travail","Information",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param evt
     */
    private void AnnulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerButtonActionPerformed
        dispose();
    }//GEN-LAST:event_AnnulerButtonActionPerformed

    /**
     * @param evt
     */
    private void solRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solRadioButtonActionPerformed
        pontComboBox.setEnabled(false);
        pontRadioButton.setSelected(true);
        pontRadioButton.setSelected(false);
    }//GEN-LAST:event_solRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PriseCharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PriseCharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PriseCharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PriseCharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Hashtable<Vector<Object>,Boolean> table = new Hashtable<>();
                Vector<Object> coucou = new Vector<>();
                coucou.add("Audi TT");
                coucou.add("1-CAC-999");
                coucou.add(new Client("Simar","Floryan","Coucou","Caca","abc"));
                coucou.add("20000km");
                coucou.add("24h");
                table.put(coucou,true);
                PriseCharge dialog = new PriseCharge(new javax.swing.JFrame(), true,table,new Travail[4]);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnulerButton;
    private javax.swing.JTable Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<String> pontComboBox;
    private javax.swing.JRadioButton pontRadioButton;
    private javax.swing.JRadioButton solRadioButton;
    // End of variables declaration//GEN-END:variables
    private Hashtable<Vector<Object>,Boolean> Liste;
    private Travail[] ListeOccupe;
}
